### ISSUE TITLE
http://bik.io/

### ISSUE THREAD

**Issue by yoanngrange** [fer/bikio#1]
for sale... ^^

**Comment by fer** [comment]
it's still soon to change the name :D what name do you propose?

**Comment by yoanngrange** [comment]
bik.io

**Comment by fer** [comment]
sorry @yoanngrange , not really sure if I understand: do you propose to buy it? JCDecaux promises to continue mantainning this API.

**Comment by yoanngrange** [comment]
clawo hombwe
